language: bash

sudo: required

before_script:
  - sudo apt-get update
  - sudo apt-get install yum

#services:
#  - docker
#
#before_install:
#  - sudo apt-get update
#  - echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null
#  - sudo service docker restart
#  - sleep 5
#  - sudo docker pull centos:centos7

script: bash test/test.sh
#script: sudo docker run --rm=true -v `pwd`:/htcondor-ce:rw centos:centos7 /bin/bash -c "bash -xe /htcondor-ce/test/test.sh"
#script: sudo docker run --rm=true -v `pwd`:/something:rw centos:centos7 /bin/bash -c "bash /something/test/test.sh"

notifications:
  email:
  - false
