language: shell

jobs:
  include:
    - name: Running on Linux
      os: linux
    - name: MacOS
      os: osx
      osx_image: xcode12.2

script:
  - bash test/test_setup_dev_env.sh
  - bash test/test_setup_ssh_keys.sh

notifications:
  email:
  - false
