language: bash

matrix:
  include:
    - os: linux
      sudo: required
#    - os: osx

#addons:
#  apt:
#    packages:
#      - yum

script:
  - bash test/test.sh
  - bash test/test_setup_ssh_keys.sh

notifications:
  email:
  - false
