language: bash

matrix:
  include:
    - os: linux
      sudo: required
    - os: osx
      osx_image: xcode12.2

script:
  - bash test/test_setup_dev_env.sh
  - bash test/test_setup_ssh_keys.sh

notifications:
  email:
  - false
