version: 2.1

executors:
  linux:
    docker:
      - image: cimg/base:2021.07
  macos:
    macos:
      xcode: "13.0.0"

jobs:
  reusable-job:
    description: "Reusable Job which takes working directory as a parameter"
    parameters:
      os:
        description: "Operating System"
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - run: |
          bash test/test_setup_dev_env.sh
          bash test/test_setup_ssh_keys.sh

workflows:
  default:
    jobs:
      - reusable-job
          matrix:
            parameters:
              os: [linux, macos]
