name: "macOS"

on: [push, pull_request]

jobs:
  build:
    name: 'Test on macOS'

    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Print version
      run: sw_vers

    - name: Test 'setup_dev_env.sh'
      working-directory: test
      run: bash test_setup_dev_env.sh

    - name: Test 'setup_ssh_keys.sh'
      working-directory: test
      run: bash test_setup_ssh_keys.sh
